spring.application.name=backend-api

server.port=8087

spring.datasource.url=jdbc:postgresql://localhost:5432/f1
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=ivonavargek
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true

spring.sql.init.mode=embedded
spring.web.resources.static-locations=classpath:/static/

backup.directory=backups
backup.pg-dump-path=pg_dump
backup.prefix=backup_
backup.extension=.sql

postgres.username=ivonavargek
postgres.database=f1
postgres.port=5432
postgres.host=localhost

