INSERT INTO drivers (code, driver_number, image_url, first_name, last_name, date_of_birth, nationality)
VALUES
    ('VER', 3, '/images/drivers/max_verstappen.jpg', 'Max', 'Verstappen', '1997-09-30', 'Dutch'),
    ('NOR', 1, '/images/drivers/lando_norris.jpg', 'Lando', 'Norris', '1999-11-13', 'British'),
    ('LEC', 16, '/images/drivers/charles_leclerc.jpeg', 'Charles', 'Leclerc', '1997-10-16', 'Monegasque'),
    ('HAM', 44, '/images/drivers/lewis_hamilton.jpg', 'Lewis', 'Hamilton', '1985-01-07', 'British'),
    ('RUS', 63, '/images/drivers/george_russell.jpeg', 'George', 'Russell', '1998-02-15', 'British'),
    ('SAI', 55, '/images/drivers/carlos_sainz.jpg', 'Carlos', 'Sainz', '1994-09-01', 'Spanish'),
    ('PIA', 81, '/images/drivers/oscar_piastri.jpg', 'Oscar', 'Piastri', '2001-04-06', 'Australian'),
    ('ALO', 14, '/images/drivers/fernando_alonso.png', 'Fernando', 'Alonso', '1981-07-29', 'Spanish'),
    ('STR', 18, '/images/drivers/lance_stroll.jpg', 'Lance', 'Stroll', '1998-10-29', 'Canadian'),
    ('GAS', 10, '/images/drivers/pierre_gasly.png', 'Pierre', 'Gasly', '1996-02-07', 'French'),
    ('OCO', 31, '/images/drivers/esteban_ocon.jpg', 'Esteban', 'Ocon', '1996-09-17', 'French'),
    ('HUL', 27, '/images/drivers/nico_hulkenberg.jpeg', 'Nico', 'Hulkenberg', '1987-08-19', 'German'),
    ('BOT', 77, '/images/drivers/valtteri_bottas.jpg', 'Valtteri', 'Bottas', '1989-08-28', 'Finnish'),
    ('ALB', 23, '/images/drivers/alexander_albon.jpeg', 'Alexander', 'Albon', '1996-03-23', 'Thai'),
    ('LAW', 30, '/images/drivers/liam_lawson.jpg', 'Liam', 'Lawson', '2002-02-11', 'New Zealander'),
    ('PER', 11, '/images/drivers/sergio_perez.jpg', 'Sergio', 'Perez', '1990-01-26', 'Mexican'),
    ('ANT', 12, '/images/drivers/andrea_kimi_antonelli.jpeg', 'Andrea Kimi', 'Antonelli', '2006-08-25', 'Italian'),
    ('BEA', 87, '/images/drivers/oliver_bearman.jpeg', 'Oliver', 'Bearman', '2005-05-08', 'British'),
    ('BOR', 5, '/images/drivers/gabriel_bortoleto.jpg', 'Gabriel', 'Bortoleto', '2004-10-14', 'Brazilian'),
    ('HAD', 6, '/images/drivers/isack_hadjar.jpeg', 'Isack', 'Hadjar', '2004-09-28', 'French'),
    ('COL', 43, '/images/drivers/franco_colapinto.jpg', 'Franco', 'Colapinto', '2003-05-27', 'Argentine'),
    ('LIN', 41, '/images/drivers/arvid_lindblad.jpg', 'Arvid', 'Lindblad', '2007-08-08', 'British');

INSERT INTO teams(full_name, short_name, base, team_chief, technical_chief, power_unit, first_team_entry, team_logo_url) VALUES
                                                                                                                       ('McLaren Mastercard F1 Team', 'McLaren', 'Woking, United Kingdom', 'Andrea Stella', 'Peter Prodromou', 'Mercedes', 1966, '/images/teams/mclaren.png'),
                                                                                                                       ('Mercedes-AMG PETRONAS Formula One Team', 'Mercedes', 'Brackley, United Kingdom', 'Toto Wolff', 'James Allison', 'Mercedes', 1970, '/images/teams/mercedes.png'),
                                                                                                                       ('Scuderia Ferrari HP', 'Ferrari', 'Maranello, Italy', 'Frédéric Vasseur', 'Loic Serra', 'Ferrari', 1950, '/images/teams/ferrari.jpg'),
                                                                                                                       ('TGR Haas F1 Team', 'Haas', 'Kannapolis, United States', 'Ayao Komatsu', 'Andrea De Zordo', 'Ferrari', 2016, '/images/teams/haas.png'),
                                                                                                                       ('BWT Alpine Formula One Team', 'Alpine', 'Enstone, United Kingdom', 'Flavio Briatore', 'David Sanchez', 'Mercedes', 1986, '/images/teams/alpine.jpg'),
                                                                                                                       ('Oracle Red Bull Racing', 'Red Bull', 'Milton Keynes, United Kingdom', 'Laurent Mekies', 'Pierre Waché', 'Red Bull Ford', 1997, '/images/teams/redbull.jpg'),
                                                                                                                       ('Visa Cash App Racing Bulls Formula One Team', 'RB', 'Faenza, Italy', 'Alan Permane', 'Tim Goss', 'Red Bull Ford', 1985, '/images/teams/rb.jpg'),
                                                                                                                       ('Audi Revolut F1 Team', 'Audi', 'Hinwil, Switzerland', 'Mattia Binotto', 'James Key', 'Audi', 2026, '/images/teams/audi.jpeg'),
                                                                                                                       ('Atlassian Williams F1 Team', 'Williams', 'Grove, United Kingdom', 'James Vowles', 'Pat Fry', 'Mercedes', 1978, '/images/teams/williams.png'),
                                                                                                                       ('Cadillac Formula 1 Team', 'Cadillac', 'Silverstone, United Kingdom', 'Graeme Lowdon', 'Nick Chester', 'Ferrari', 2026, '/images/teams/cadillac.png'),
                                                                                                                       ('Aston Martin Aramco Formula One Team', 'Aston Martin', 'Silverstone, United Kingdom', 'Adrian Newey', 'Enrico Cardile', 'Honda', 2018, '/images/teams/aston.jpg');

INSERT INTO circuits (track_name, country, city, circuit_length, first_grand_prix, number_of_laps, race_distance, fastest_lap_time, circuit_image_url)
VALUES
    ('Albert Park Circuit', 'Australia', 'Melbourne', 5.278, 1996, 58, 306.124, '1:19.813',  '/images/circuits/australia.png'),
    ('Shanghai International Circuit', 'China', 'Shanghai', 5.451, 2004, 56, 305.066, '1:32.238', '/images/circuits/china.png'),
    ('Suzuka Circuit', 'Japan', 'Suzuka', 5.807, 1987, 53, 307.471, '1:30.965', '/images/circuits/japan.png'),
    ('Miami International Autodrome', 'United States', 'Miami', 5.412, 2022, 57, 308.326, '1:29.708', '/images/circuits/miami.png'),
    ('Circuit Gilles Villeneuve', 'Canada', 'Montreal', 4.361, 1978, 70, 305.27, '1:13.078', '/images/circuits/canada.png'),
    ('Circuit de Monaco', 'Monaco', 'Monaco', 3.337, 1950, 78, 260.286, '1:12.909', '/images/circuits/monaco.png'),
    ('Circuit de Barcelona-Catalunya', 'Spain', 'Montmeló', 4.657, 1991, 66, 307.236, '1:15.743', '/images/circuits/barcelona.png'),
    ('Red Bull Ring', 'Austria', 'Spielberg', 4.326, 1970, 71, 307.018, '1:07.924', '/images/circuits/austria.png'),
    ('Silverstone Circuit', 'United Kingdom', 'Silverstone', 5.891, 1950, 52, 306.198, '1:27.097', '/images/circuits/silverstone.png'),
    ('Circuit de Spa-Francorchamps', 'Belgium', 'Stavelot', 7.004, 1950, 44, 308.052, '1:44.701', '/images/circuits/spa.png'),
    ('Hungaroring', 'Hungary', 'Mogyoród', 4.381, 1986, 70, 306.63, '1:16.627', '/images/circuits/hungary.png'),
    ('Circuit Zandvoort', 'Netherlands', 'Zandvoort', 4.259, 1952, 72, 306.587, '1:11.097', '/images/circuits/zandvoort.png'),
    ('Autodromo Nazionale Monza', 'Italy', 'Monza', 5.793, 1950, 53, 306.72, '1:20.901', '/images/circuits/monza.png'),
    ('Madring Circuit', 'Spain', 'Madrid', 5.416, 2026, 57, 308.524, 'Not set', '/images/circuits/madrid.png'),
    ('Baku City Circuit', 'Azerbaijan', 'Baku', 6.003, 2016, 51, 306.049, '1:43.009', '/images/circuits/baku.png'),
    ('Marina Bay Street Circuit', 'Singapore', 'Singapore', 4.927, 2008, 62, 305.337, '1:33.808', '/images/circuits/singapore.png'),
    ('Circuit of the Americas', 'United States', 'Austin', 5.513, 2012, 56, 308.405, '1:36.169', '/images/circuits/americas.png'),
    ('Autódromo Hermanos Rodríguez', 'Mexico', 'Mexico City', 4.304, 1963, 71, 305.354, '1:17.774', '/images/circuits/mexico.png'),
    ('Autódromo José Carlos Pace', 'Brazil', 'São Paulo', 4.309, 1973, 71, 305.879, '1:10.540', '/images/circuits/brazil.png'),
    ('Las Vegas Street Circuit', 'United States', 'Las Vegas', 6.201, 2023, 50, 309.958, '1:33.365', '/images/circuits/lasvegas.png'),
    ('Lusail International Circuit', 'Qatar', 'Lusail', 5.419, 2021, 57, 308.611, '1:22.384', '/images/circuits/lusail.png'),
    ('Yas Marina Circuit', 'United Arab Emirates', 'Abu Dhabi', 5.281, 2009, 58, 306.183, '1:25.637', '/images/circuits/yas.png');
